# Generated by Django 4.2.6 on 2023-10-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_comment_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['pub_date'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
