# Generated by Django 4.2.6 on 2023-10-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='site_address',
            field=models.URLField(default=12, verbose_name='Адрес сайта'),
            preserve_default=False,
        ),
    ]
