# Generated by Django 4.2.6 on 2023-10-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagservice',
            options={'ordering': ['tag'], 'verbose_name_plural': 'Tags Activities'},
        ),
    ]
