# Generated by Django 4.2.6 on 2023-11-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='about_master',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
    ]
