# Generated by Django 4.2.6 on 2023-10-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_site_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='site_address',
            field=models.URLField(blank=True, null=True, verbose_name='Адрес сайта'),
        ),
    ]
