# Generated by Django 4.2.6 on 2023-10-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_tagservice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityservice',
            options={'ordering': ['activity'], 'verbose_name_plural': 'Activity Services'},
        ),
        migrations.AlterModelOptions(
            name='locationservice',
            options={'ordering': ['location'], 'verbose_name_plural': 'Location Services'},
        ),
        migrations.AlterModelOptions(
            name='tagactivity',
            options={'ordering': ['tag'], 'verbose_name_plural': 'Tags Activities'},
        ),
        migrations.AlterModelOptions(
            name='tagservice',
            options={'ordering': ['tag'], 'verbose_name_plural': 'Tags Services'},
        ),
    ]
