# Generated by Django 4.2.6 on 2023-11-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_about_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'default_related_name': 'services', 'ordering': ['-created'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
