# Generated by Django 4.2.6 on 2023-10-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_site_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.AddField(
            model_name='location',
            name='building',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Корпус/Строение'),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default=1, max_length=50, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default=1, max_length=50, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='house_number',
            field=models.IntegerField(default=123, verbose_name='Номер дома'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='office_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Офис'),
        ),
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.CharField(default=123, max_length=100, verbose_name='Улица'),
            preserve_default=False,
        ),
    ]
