# Generated by Django 4.2.6 on 2023-10-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_activityservice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityservice',
            options={'ordering': ['activity'], 'verbose_name_plural': 'Activities Services'},
        ),
        migrations.AlterModelOptions(
            name='locationservice',
            options={'ordering': ['location'], 'verbose_name_plural': 'Locations Services'},
        ),
    ]
