# Generated by Django 4.2.6 on 2023-10-08 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0006_alter_activityservice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_favorite_for_users', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['service'],
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='tags',
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TagActivity',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'service'), name='unique_favorite'),
        ),
    ]
