# Generated by Django 4.2.6 on 2023-10-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_favorite_remove_activity_tags_activity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/image/', verbose_name='Фото'),
        ),
    ]
