# Generated by Django 4.2.6 on 2023-10-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='services/image/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
