# Generated by Django 4.2.6 on 2023-10-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_site_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='site_address',
        ),
    ]
