# Generated by Django 4.2.6 on 2023-11-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_master_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
    ]
