# Generated by Django 4.2.6 on 2023-11-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_master',
            field=models.BooleanField(verbose_name='Статус Мастера'),
        ),
    ]
