# Generated by Django 4.2.6 on 2023-10-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='foto',
            new_name='photo',
        ),
    ]
