# Generated by Django 4.2.6 on 2023-11-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_bio_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/image/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Статус Клиента'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='Статус Мастера'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
    ]
