# Generated by Django 4.2.6 on 2023-11-02 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_master_user_customuser_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_client',
        ),
    ]
