# Generated by Django 4.2.6 on 2023-11-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=1, max_length=11, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
